name: HotelListe
on:
  push:
    branches:
      - heroku
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          HOTEL_DB_URL: ${{ secrets.HOTEL_DB_URL }}
          HOTEL_DB_USER: ${{ secrets.HOTEL_DB_USER }}
          HOTEL_DB_PASSWORD: ${{ secrets.HOTEL_DB_PASSWORD }}
        run: mvn --batch-mode --update-snapshots verify