name: HotelListe

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        env:
          HOTEL_DB_URL: ${{ secrets.HOTEL_DB_URL }}
          HOTEL_DB_USER: ${{ secrets.HOTEL_DB_USER }}
          HOTEL_DB_PASSWORD: ${{ secrets.HOTEL_DB_PASSWORD }}
        run: echo ${SONAR_TOKEN}
             echo ${HOTEL_DB_URL}
             mvn --batch-mode --update-snapshots verify